#!/usr/bin/env bash
# local-dev-install.sh — Install cm as a bun wrapper pointing at local source
#
# This is the recommended local development install. Instead of compiling a
# standalone binary (which has ONNX bundling issues), we install a thin shell
# wrapper that invokes `bun run src/cm.ts` directly. This means:
#
#   - cm always reflects the current HEAD of this repo
#   - No compile/rebuild step needed after `git pull`
#   - The post-merge hook is a no-op unless bun deps changed
#
# For production releases, the CI cross-compiles from Linux and uploads
# prebuilt binaries to GitHub Releases. Use install.sh for those.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${DEST:-$HOME/.local/bin}"
BINARY="cm"
TARGET="$DEST/$BINARY"

mkdir -p "$DEST"

printf '#!/usr/bin/env bash\n# cm — local dev wrapper (auto-generated by scripts/local-dev-install.sh)\nexec bun run %s/src/cm.ts "$@"\n' "$REPO_ROOT" > "$TARGET"
chmod +x "$TARGET"

VERSION=$("$TARGET" --version 2>/dev/null || echo "unknown")
echo "✓ Installed cm $VERSION → $TARGET  (wrapper → $REPO_ROOT/src/cm.ts)"
